services:
  - type: web
    name: iddaw-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: project
    buildCommand: pip install -r requirements_backend.txt
    startCommand: python start_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

  - type: web
    name: iddaw-frontend
    env: static
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build:client
    staticPublishPath: dist/spa
    envVars:
      - key: VITE_API_BASE_URL
        value: https://adverse-weather-safe-segmentation.onrender.com
      - key: VITE_USE_MOCKS
        value: "false"
